# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registerform(object):
    def setupUi(self, Registerform):
        Registerform.setObjectName("Registerform")
        Registerform.resize(202, 261)
        Registerform.setAutoFillBackground(False)
        Registerform.setStyleSheet("background-color: rgb(25, 25, 25);")
        self.username = QtWidgets.QLineEdit(Registerform)
        self.username.setGeometry(QtCore.QRect(40, 70, 113, 20))
        self.username.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.username.setObjectName("username")
        self.email = QtWidgets.QLineEdit(Registerform)
        self.email.setGeometry(QtCore.QRect(40, 100, 113, 20))
        self.email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email.setObjectName("email")
        self.confirmpass = QtWidgets.QLineEdit(Registerform)
        self.confirmpass.setGeometry(QtCore.QRect(40, 170, 113, 20))
        self.confirmpass.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.confirmpass.setObjectName("confirmpass")
        self.password = QtWidgets.QLineEdit(Registerform)
        self.password.setGeometry(QtCore.QRect(40, 140, 113, 20))
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password.setObjectName("password")
        self.Register = QtWidgets.QPushButton(Registerform)
        self.Register.setGeometry(QtCore.QRect(60, 200, 75, 23))
        self.Register.setStyleSheet("\n"
"color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 7px;")
        self.Register.setAutoDefault(False)
        self.Register.setDefault(True)
        self.Register.setFlat(False)
        self.Register.setObjectName("Register")
        self.Cancel = QtWidgets.QPushButton(Registerform)
        self.Cancel.setGeometry(QtCore.QRect(60, 230, 75, 23))
        self.Cancel.setStyleSheet("\n"
"color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 7px;")
        self.Cancel.setDefault(True)
        self.Cancel.setFlat(False)
        self.Cancel.setObjectName("Cancel")
        self.TOSbutton = QtWidgets.QPushButton(Registerform)
        self.TOSbutton.setGeometry(QtCore.QRect(150, 0, 51, 20))
        self.TOSbutton.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 7px;")
        self.TOSbutton.setDefault(True)
        self.TOSbutton.setObjectName("TOSbutton")
        self.label = QtWidgets.QLabel(Registerform)
        self.label.setGeometry(QtCore.QRect(70, 10, 51, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/LOGO.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Registerform)
        QtCore.QMetaObject.connectSlotsByName(Registerform)

    def retranslateUi(self, Registerform):
        _translate = QtCore.QCoreApplication.translate
        Registerform.setWindowTitle(_translate("Registerform", "Register"))
        self.username.setPlaceholderText(_translate("Registerform", "Username"))
        self.email.setPlaceholderText(_translate("Registerform", "Email"))
        self.confirmpass.setPlaceholderText(_translate("Registerform", "Confirm Password"))
        self.password.setPlaceholderText(_translate("Registerform", "Password"))
        self.Register.setText(_translate("Registerform", "Register"))
        self.Cancel.setText(_translate("Registerform", "Cancel"))
        self.TOSbutton.setText(_translate("Registerform", "TOS"))
