# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Xpense(object):
    def setupUi(self, Xpense):
        Xpense.setObjectName("Xpense")
        Xpense.resize(485, 384)
        Xpense.setWindowOpacity(1.0)
        Xpense.setStyleSheet("background-color: rgb(25, 25, 25);")
        self.centralwidget = QtWidgets.QWidget(Xpense)
        self.centralwidget.setObjectName("centralwidget")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(200, 270, 121, 41))
        self.login.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 7px;")
        self.login.setObjectName("login")
        self.register_2 = QtWidgets.QPushButton(self.centralwidget)
        self.register_2.setGeometry(QtCore.QRect(200, 200, 121, 41))
        self.register_2.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 7px;")
        self.register_2.setObjectName("register_2")
        self.TOSbutton = QtWidgets.QPushButton(self.centralwidget)
        self.TOSbutton.setGeometry(QtCore.QRect(410, 0, 75, 23))
        self.TOSbutton.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 7px;")
        self.TOSbutton.setDefault(True)
        self.TOSbutton.setObjectName("TOSbutton")
        self.Privacy = QtWidgets.QPushButton(self.centralwidget)
        self.Privacy.setGeometry(QtCore.QRect(410, 30, 75, 23))
        self.Privacy.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 7px;")
        self.Privacy.setDefault(True)
        self.Privacy.setObjectName("Privacy")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(180, 30, 161, 151))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../../../Downloads/LOGO.jpg"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        Xpense.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Xpense)
        self.statusbar.setObjectName("statusbar")
        Xpense.setStatusBar(self.statusbar)

        self.retranslateUi(Xpense)
        QtCore.QMetaObject.connectSlotsByName(Xpense)

    def retranslateUi(self, Xpense):
        _translate = QtCore.QCoreApplication.translate
        Xpense.setWindowTitle(_translate("Xpense", "Xpense"))
        self.login.setText(_translate("Xpense", "Login"))
        self.register_2.setText(_translate("Xpense", "Register"))
        self.TOSbutton.setText(_translate("Xpense", "TOS"))
        self.Privacy.setText(_translate("Xpense", "Privacy Policy"))
