# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'curr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(354, 185)
        self.convert = QtWidgets.QPushButton(Dialog)
        self.convert.setGeometry(QtCore.QRect(140, 140, 75, 23))
        self.convert.setObjectName("convert")
        self.inp_value = QtWidgets.QLineEdit(Dialog)
        self.inp_value.setGeometry(QtCore.QRect(50, 60, 81, 41))
        self.inp_value.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_value.setObjectName("inp_value")
        self.out_val = QtWidgets.QTextBrowser(Dialog)
        self.out_val.setGeometry(QtCore.QRect(220, 60, 81, 41))
        self.out_val.setStyleSheet("text-align:center;")
        self.out_val.setObjectName("out_val")
        self.inp_curr = QtWidgets.QComboBox(Dialog)
        self.inp_curr.setGeometry(QtCore.QRect(50, 30, 81, 22))
        self.inp_curr.setObjectName("inp_curr")
        self.out_curr = QtWidgets.QComboBox(Dialog)
        self.out_curr.setGeometry(QtCore.QRect(220, 30, 81, 22))
        self.out_curr.setObjectName("out_curr")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 40, 71, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.convert.setText(_translate("Dialog", "Convert"))
        self.label.setText(_translate("Dialog", "TO"))
