# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prod.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(352, 88)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 331, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ProdInfo = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.ProdInfo.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\"\n"
"")
        self.ProdInfo.setObjectName("ProdInfo")
        self.horizontalLayout.addWidget(self.ProdInfo)
        self.ProdImage = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ProdImage.setAlignment(QtCore.Qt.AlignCenter)
        self.ProdImage.setObjectName("ProdImage")
        self.horizontalLayout.addWidget(self.ProdImage)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel.sizePolicy().hasHeightForWidth())
        self.cancel.setSizePolicy(sizePolicy)
        self.cancel.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel.setIcon(icon)
        self.cancel.setObjectName("cancel")
        self.verticalLayout.addWidget(self.cancel)
        self.transfer = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transfer.sizePolicy().hasHeightForWidth())
        self.transfer.setSizePolicy(sizePolicy)
        self.transfer.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/transfer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transfer.setIcon(icon1)
        self.transfer.setObjectName("transfer")
        self.verticalLayout.addWidget(self.transfer)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ProdImage.setText(_translate("Form", "Product Image"))
        self.cancel.setToolTip(_translate("Form", "Remove Item"))
        self.transfer.setToolTip(_translate("Form", "Transfer to Recently Bought."))
