# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMainWindow(object):
    def setupUi(self, MainMainWindow):
        MainMainWindow.setObjectName("MainMainWindow")
        MainMainWindow.resize(961, 580)
        MainMainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.orderscrolla = QtWidgets.QScrollArea(self.centralwidget)
        self.orderscrolla.setGeometry(QtCore.QRect(0, 210, 276, 312))
        self.orderscrolla.setStyleSheet("")
        self.orderscrolla.setWidgetResizable(True)
        self.orderscrolla.setObjectName("orderscrolla")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 257, 1244))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.t1 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t1.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\"\n"
"")
        self.t1.setObjectName("t1")
        self.verticalLayout.addWidget(self.t1)
        self.t2 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t2.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t2.setObjectName("t2")
        self.verticalLayout.addWidget(self.t2)
        self.t3 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t3.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t3.setObjectName("t3")
        self.verticalLayout.addWidget(self.t3)
        self.t4 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t4.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t4.setObjectName("t4")
        self.verticalLayout.addWidget(self.t4)
        self.t5 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t5.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t5.setObjectName("t5")
        self.verticalLayout.addWidget(self.t5)
        self.t6 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t6.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t6.setObjectName("t6")
        self.verticalLayout.addWidget(self.t6)
        self.t7 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t7.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t7.setObjectName("t7")
        self.verticalLayout.addWidget(self.t7)
        self.t8 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t8.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t8.setObjectName("t8")
        self.verticalLayout.addWidget(self.t8)
        self.t9 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t9.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t9.setObjectName("t9")
        self.verticalLayout.addWidget(self.t9)
        self.t10 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t10.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t10.setObjectName("t10")
        self.verticalLayout.addWidget(self.t10)
        self.t11 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t11.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t11.setObjectName("t11")
        self.verticalLayout.addWidget(self.t11)
        self.t12 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t12.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t12.setObjectName("t12")
        self.verticalLayout.addWidget(self.t12)
        self.t13 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t13.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t13.setObjectName("t13")
        self.verticalLayout.addWidget(self.t13)
        self.t14 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t14.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t14.setObjectName("t14")
        self.verticalLayout.addWidget(self.t14)
        self.t15 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t15.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t15.setObjectName("t15")
        self.verticalLayout.addWidget(self.t15)
        self.t16 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.t16.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t16.setObjectName("t16")
        self.verticalLayout.addWidget(self.t16)
        self.orderscrolla.setWidget(self.scrollAreaWidgetContents)
        self.Totalexpend = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend.setGeometry(QtCore.QRect(220, 0, 261, 81))
        self.Totalexpend.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend.setObjectName("Totalexpend")
        self.searchscrolla = QtWidgets.QScrollArea(self.centralwidget)
        self.searchscrolla.setGeometry(QtCore.QRect(280, 210, 276, 312))
        self.searchscrolla.setWidgetResizable(True)
        self.searchscrolla.setObjectName("searchscrolla")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 257, 1244))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.t18 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t18.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t18.setObjectName("t18")
        self.verticalLayout_2.addWidget(self.t18)
        self.t19 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t19.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t19.setObjectName("t19")
        self.verticalLayout_2.addWidget(self.t19)
        self.t20 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t20.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t20.setObjectName("t20")
        self.verticalLayout_2.addWidget(self.t20)
        self.t22 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t22.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t22.setObjectName("t22")
        self.verticalLayout_2.addWidget(self.t22)
        self.t23 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t23.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t23.setObjectName("t23")
        self.verticalLayout_2.addWidget(self.t23)
        self.t24 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t24.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t24.setObjectName("t24")
        self.verticalLayout_2.addWidget(self.t24)
        self.t25 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t25.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t25.setObjectName("t25")
        self.verticalLayout_2.addWidget(self.t25)
        self.t26 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t26.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t26.setObjectName("t26")
        self.verticalLayout_2.addWidget(self.t26)
        self.t27 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t27.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t27.setObjectName("t27")
        self.verticalLayout_2.addWidget(self.t27)
        self.t28 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t28.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t28.setObjectName("t28")
        self.verticalLayout_2.addWidget(self.t28)
        self.t29 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t29.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t29.setObjectName("t29")
        self.verticalLayout_2.addWidget(self.t29)
        self.t30 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t30.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t30.setObjectName("t30")
        self.verticalLayout_2.addWidget(self.t30)
        self.t31 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t31.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t31.setObjectName("t31")
        self.verticalLayout_2.addWidget(self.t31)
        self.t32 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t32.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t32.setObjectName("t32")
        self.verticalLayout_2.addWidget(self.t32)
        self.t33 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t33.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t33.setObjectName("t33")
        self.verticalLayout_2.addWidget(self.t33)
        self.t34 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.t34.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255);\n"
"font: 8pt \"Leelawadee\";\n"
"")
        self.t34.setObjectName("t34")
        self.verticalLayout_2.addWidget(self.t34)
        self.searchscrolla.setWidget(self.scrollAreaWidgetContents_2)
        self.Totalexpend_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend_2.setGeometry(QtCore.QRect(10, 170, 241, 41))
        self.Totalexpend_2.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend_2.setObjectName("Totalexpend_2")
        self.Totalexpend_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend_3.setGeometry(QtCore.QRect(290, 170, 241, 41))
        self.Totalexpend_3.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend_3.setObjectName("Totalexpend_3")
        self.Totalexpend_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend_4.setGeometry(QtCore.QRect(240, 40, 231, 41))
        self.Totalexpend_4.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend_4.setObjectName("Totalexpend_4")
        self.Totalexpend_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend_5.setGeometry(QtCore.QRect(490, 0, 241, 81))
        self.Totalexpend_5.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend_5.setObjectName("Totalexpend_5")
        self.MonthProgress = QtWidgets.QProgressBar(self.centralwidget)
        self.MonthProgress.setGeometry(QtCore.QRect(500, 50, 111, 23))
        self.MonthProgress.setProperty("value", 24)
        self.MonthProgress.setObjectName("MonthProgress")
        self.Totalexpend_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend_6.setGeometry(QtCore.QRect(490, 30, 121, 51))
        self.Totalexpend_6.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 255);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend_6.setObjectName("Totalexpend_6")
        self.YearProgress = QtWidgets.QProgressBar(self.centralwidget)
        self.YearProgress.setGeometry(QtCore.QRect(620, 50, 111, 23))
        self.YearProgress.setProperty("value", 24)
        self.YearProgress.setObjectName("YearProgress")
        self.Totalexpend_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend_7.setGeometry(QtCore.QRect(610, 30, 121, 51))
        self.Totalexpend_7.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 255);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend_7.setObjectName("Totalexpend_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(880, 10, 71, 31))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/settings.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        MainMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 21))
        self.menubar.setObjectName("menubar")
        MainMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainMainWindow)
        self.statusbar.setObjectName("statusbar")
        MainMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainMainWindow)

    def retranslateUi(self, MainMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainMainWindow.setWindowTitle(_translate("MainMainWindow", "MainWindow"))
        self.Totalexpend.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Total Expenditure This Month</span></p></body></html>"))
        self.Totalexpend_2.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Your Orders</span></p></body></html>"))
        self.Totalexpend_3.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Recently Bought</span></p></body></html>"))
        self.Totalexpend_4.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">$1000</span></p></body></html>"))
        self.Totalexpend_5.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">April 3rd 2023</span></p></body></html>"))
        self.Totalexpend_6.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Month Progress</span></p></body></html>"))
        self.Totalexpend_7.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Year Progress</span></p></body></html>"))
        self.pushButton.setText(_translate("MainMainWindow", "Settings"))
