# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMainWindow(object):
    def setupUi(self, MainMainWindow):
        MainMainWindow.setObjectName("MainMainWindow")
        MainMainWindow.resize(1100, 535)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainMainWindow.sizePolicy().hasHeightForWidth())
        MainMainWindow.setSizePolicy(sizePolicy)
        MainMainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.orderscrolla = QtWidgets.QScrollArea(self.centralwidget)
        self.orderscrolla.setGeometry(QtCore.QRect(10, 160, 351, 312))
        self.orderscrolla.setStyleSheet("")
        self.orderscrolla.setWidgetResizable(True)
        self.orderscrolla.setObjectName("orderscrolla")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 349, 310))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.orderscrolla.setWidget(self.scrollAreaWidgetContents)
        self.Totalexpend = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend.setGeometry(QtCore.QRect(220, 0, 261, 81))
        self.Totalexpend.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend.setObjectName("Totalexpend")
        self.recently = QtWidgets.QScrollArea(self.centralwidget)
        self.recently.setGeometry(QtCore.QRect(370, 160, 351, 312))
        self.recently.setWidgetResizable(True)
        self.recently.setObjectName("recently")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 349, 310))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.recently.setWidget(self.scrollAreaWidgetContents_2)
        self.Totalexpend_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend_2.setGeometry(QtCore.QRect(10, 120, 251, 41))
        self.Totalexpend_2.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend_2.setObjectName("Totalexpend_2")
        self.Totalexpend_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend_3.setGeometry(QtCore.QRect(370, 120, 251, 41))
        self.Totalexpend_3.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend_3.setObjectName("Totalexpend_3")
        self.Totalexpend_5_T = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend_5_T.setGeometry(QtCore.QRect(490, 0, 241, 81))
        self.Totalexpend_5_T.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend_5_T.setObjectName("Totalexpend_5_T")
        self.MonthProgress = QtWidgets.QProgressBar(self.centralwidget)
        self.MonthProgress.setGeometry(QtCore.QRect(500, 50, 111, 23))
        self.MonthProgress.setProperty("value", 24)
        self.MonthProgress.setObjectName("MonthProgress")
        self.Totalexpend_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend_6.setGeometry(QtCore.QRect(490, 30, 121, 51))
        self.Totalexpend_6.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 255);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend_6.setObjectName("Totalexpend_6")
        self.YearProgress = QtWidgets.QProgressBar(self.centralwidget)
        self.YearProgress.setGeometry(QtCore.QRect(620, 50, 111, 23))
        self.YearProgress.setProperty("value", 24)
        self.YearProgress.setObjectName("YearProgress")
        self.Totalexpend_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend_7.setGeometry(QtCore.QRect(610, 30, 121, 51))
        self.Totalexpend_7.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 255);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend_7.setObjectName("Totalexpend_7")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(270, 130, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.Add.setFont(font)
        self.Add.setObjectName("Add")
        self.Add_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Add_2.setGeometry(QtCore.QRect(630, 130, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.Add_2.setFont(font)
        self.Add_2.setObjectName("Add_2")
        self.search = QtWidgets.QScrollArea(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(730, 161, 351, 311))
        self.search.setWidgetResizable(True)
        self.search.setObjectName("search")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 349, 309))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.search.setWidget(self.scrollAreaWidgetContents_3)
        self.Totalexpend_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Totalexpend_8.setGeometry(QtCore.QRect(760, 90, 291, 41))
        self.Totalexpend_8.setStyleSheet("color: rgb(0,0,0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255,255,255,0);\n"
"font: 25 11pt \"Yu Gothic Light\";\n"
"")
        self.Totalexpend_8.setObjectName("Totalexpend_8")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(760, 130, 261, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1020, 130, 31, 21))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 51, 51))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("static/LOGOproject.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(830, 470, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(11)
        self.status.setFont(font)
        self.status.setText("")
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.loading = QtWidgets.QLabel(self.centralwidget)
        self.loading.setGeometry(QtCore.QRect(710, 470, 31, 31))
        self.loading.setText("")
        self.loading.setObjectName("loading")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(740, 0, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.clear.setFont(font)
        self.clear.setStyleSheet("border-color: rgb(255, 47, 47);\n"
"color: rgb(255, 0, 0);\n"
"color: rgb(170, 0, 0);\n"
"font: 75 8pt \"Unispace\";")
        self.clear.setObjectName("clear")
        self.calendar = QtWidgets.QPushButton(self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(900, 0, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.calendar.setFont(font)
        self.calendar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/calender.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calendar.setIcon(icon1)
        self.calendar.setObjectName("calendar")
        self.currencies = QtWidgets.QComboBox(self.centralwidget)
        self.currencies.setGeometry(QtCore.QRect(230, 40, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.currencies.setFont(font)
        self.currencies.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.currencies.setEditable(False)
        self.currencies.setCurrentText("")
        self.currencies.setObjectName("currencies")
        self.calendar_2 = QtWidgets.QPushButton(self.centralwidget)
        self.calendar_2.setGeometry(QtCore.QRect(910, 30, 131, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.calendar_2.setFont(font)
        self.calendar_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/conv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calendar_2.setIcon(icon2)
        self.calendar_2.setObjectName("calendar_2")
        self.status_2 = QtWidgets.QLabel(self.centralwidget)
        self.status_2.setGeometry(QtCore.QRect(450, 470, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(11)
        self.status_2.setFont(font)
        self.status_2.setText("")
        self.status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.status_2.setObjectName("status_2")
        self.Totalexpend_4 = QtWidgets.QLabel(self.centralwidget)
        self.Totalexpend_4.setGeometry(QtCore.QRect(290, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        self.Totalexpend_4.setFont(font)
        self.Totalexpend_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Totalexpend_4.setObjectName("Totalexpend_4")
        self.Totalexpend_5 = QtWidgets.QLabel(self.centralwidget)
        self.Totalexpend_5.setGeometry(QtCore.QRect(490, -20, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(14)
        self.Totalexpend_5.setFont(font)
        self.Totalexpend_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Totalexpend_5.setObjectName("Totalexpend_5")
        MainMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainMainWindow)
        self.statusbar.setObjectName("statusbar")
        MainMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainMainWindow)

    def retranslateUi(self, MainMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainMainWindow.setWindowTitle(_translate("MainMainWindow", "MainWindow"))
        self.Totalexpend.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Total Expenditure This Month</span></p></body></html>"))
        self.Totalexpend_2.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Your Orders</span></p></body></html>"))
        self.Totalexpend_3.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Recently Bought</span></p></body></html>"))
        self.Totalexpend_5_T.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Totalexpend_6.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Month Progress</span></p></body></html>"))
        self.Totalexpend_7.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Year Progress</span></p></body></html>"))
        self.Add.setText(_translate("MainMainWindow", "Add Items"))
        self.Add_2.setText(_translate("MainMainWindow", "Add Items"))
        self.Totalexpend_8.setHtml(_translate("MainMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Search Products</span></p></body></html>"))
        self.clear.setText(_translate("MainMainWindow", "Clear Session Data"))
        self.calendar.setText(_translate("MainMainWindow", "Open Calendar"))
        self.calendar_2.setText(_translate("MainMainWindow", "Convert Currency"))
        self.Totalexpend_4.setText(_translate("MainMainWindow", "0"))
        self.Totalexpend_5.setText(_translate("MainMainWindow", "April 3rd 2023"))
